### ISSUE TITLE
RedGreen for XCTest causes 100% passing tests to report failed in xcode

### ISSUE THREAD

**Issue by SRandazzo** [neilco/RedGreen#5]
I've started a branch that resolves some XCTest issues and also cleans the podspec up so that you can now specify subspec's for XCTest or SenTestingKit:

`pod 'RedGreen/XCTest'`
or
`pod 'RedGreen/SenTestingKit`

The default is currently SenTestingKit for compatibility sake, feel free to change if you want!
https://github.com/SRandazzo/RedGreen/tree/xctest_fixes

Beyond this however, I have been trying to identify why XCTestLog+RedGreen causes XCode to report "Tests Failed" at the end of 100% succeeding tests

`Executed 96 tests, with 0 failures (0 unexpected) in 3.784 (3.817) seconds`
`Xcode: Test Failed`

If i turn off the method swizzling in XCTestLog+RedGreen, XCode reports succes, if i turn it back on, fails

Any idea?

**Comment by SRandazzo** [comment]
@mralexgray any idea why the XCTests would be doing this?

**Comment by SRandazzo** [comment]
Just confirmed latest version of xcode which fixes "tests that report failure after succeeding" does not resolve this issue :-/

**Comment by mralexgray** [comment]
I have no idea why this is happening... i read somewhere on the xctool issues pages that it has to do with the asynchronous nature of the test bundle loading process..  are you saying that for you... this is RedGreen related?  i hate the fact that the tests fail.. and may have red green lurking around somewhere..  is that why??  or is this just Xcode being dumb..  i saw that release note, too, and can confirm, that 5.1.1 does NOT fix it for me, either.

**Comment by SRandazzo** [comment]
It's quite strange :-/

What confirmed for me that it is directly related to RedGreen is that if I **comment off** the method swizzling for XCTestLog+RedGreen, the final test result succeeds. Comment the swizzling back on and run, and it reports a failure!

**Comment by neilco** [comment]
Hi guys, 

Apologies for not responding sooner. For whatever reason, GitHub had unwatched this repo for me and I did see this issue until today. 

I've spent some time digging into this and have uncovered some useful insights. Firstly, I'll address method swizzling. With the XCTest framework, method swizzling to override the log methods is categorically **_not_** the correct way to do this. XCTest provides two routes for accessing the output from running tests: either subclass `XCTestLog` or, if you require redirecting output to something other than stderr, `XCTestObserver`. Subclassing `XCTestLog` is the simplest option so that's what I will explore here. 

To get Xcode to use the subclass (and only the subclass<sup>1</sup>), it's simply a matter of setting the name of the subclass as the `XCTestObserverClassKey` user default.

```
+ (void)load
{
    // Register this class as the only XCTestObserver to be used with this target
    [[NSUserDefaults standardUserDefaults] setValue:NSStringFromClass(self)
                                             forKey:XCTestObserverClassKey];
}
```

This can be done inside the subclass. Next,  override `-testLogWithFormat:arguments:`. Job done. A very rudimentary implementation without XcodeColors support would look like this:

```
#import "RedGreenXCTestLog.h"

NSString *const kXCTTestCaseArgsFormat = @"%@|%s|%.3f";
NSString *const kRGArgsSeparator = @"|";
NSString *const kRGTestCaseFinishFormat = @"Test Case '%@' %s (%.3f seconds).\n";
NSString *const kRGModifiedTestResultFormat = @"%@: %@ (%@s)\n";

@implementation RedGreenXCTestLog

+ (void)load
{
    [[NSUserDefaults standardUserDefaults] setValue:NSStringFromClass(self)
                                             forKey:XCTestObserverClassKey];
}

- (void)testLogWithFormat:(NSString *)format arguments:(va_list)arguments
{
    if (![format isEqualToString:kRGTestCaseFinishFormat]) {
        return;
    }

    NSArray *args = NSArrayFromArguments(arguments);
    NSString *testCase = args[0];
    NSString *result = [args[1] uppercaseString];
    NSString *duration = args[2];

    NSString *formattedLog = [NSString stringWithFormat:kRGModifiedTestResultFormat, result, testCase, duration];

    [self.logFileHandle writeData:[formattedLog dataUsingEncoding:NSUTF8StringEncoding]];
}

NSArray *NSArrayFromArguments(va_list arguments)
{
    NSString *s = [[NSString alloc] initWithFormat:kXCTTestCaseArgsFormat arguments:arguments];
    NSArray *args = [s componentsSeparatedByString:kRGArgsSeparator];

    return args;
}

@end
```

Nice and clean and simple. Running this with xcodebuild I see this (after all the build details):

```
PASSED: -[RGTestsTests testExample] (0.101s)
** TEST SUCCEEDED **
```

Brilliant. Not only did the test pass, but the output is in the abbreviated form that I want. 

Now, if you run this in Xcode via the Test Navigator (or simply hitting Cmd+U), you'll see `PASSED: -[RGTestsTests testExample] (0.101s)` in the console, all the tests will be green in Test Navigator, but you'll see a Test Failed HUD and in the Log Navigator you'll see a warning:

```
Test target <Test Target Name> did not finish
```

Why is that?

It's because **Xcode is directly parsing the test output written to stderr**. Since the format of the output has changed, Xcode fails to parse it and throws a hissy fit. 

![](http://www.spacetimestudios.com/attachment.php?attachmentid=60743&d=1391358899)

Apple have given us a wonderful feature in the ability to create custom test observers, but as soon as you modify any of the output to stderr Xcode stops reporting the true outcome of running your test suites. I don't know about you, but to me that smells like a bug. 

---

<sup>1</sup> You can specify more than one test observer setting the value of the `XCTestObserverClassKey` user default to a comma-separated list.

**Comment by neilco** [comment]
I've reported the issue to Apple as [rdar://16689070](http://openradar.appspot.com/radar?id=5873033575137280). 

If Apple are going to allow us to completely remove XCTestLog from the test reporter pipeline used by the test runner, then Xcode should not be reporting false information. Let's hope Apple agrees and resolves this issue.
